[slurm]
# Define directories for SLURM job scripts and logs:
job_dir = "/g100_work/optim_IAC/research/noc/otooth/OptimESM/WP5/data/MOHC/jobs"
log_dir = "/g100_work/optim_IAC/research/noc/otooth/OptimESM/WP5/data/MOHC/logs"
log_prefix = "UKESM1-2-LL_siarea"
# SLURM batch job submission parameters:
sbatch_job_name = "nemo_pipeline_ukesm1"
sbatch_time = "00:10:00"
sbatch_partition = ""
sbatch_ntasks = 1
sbatch_mem = "4G"
# Define the initial, final and step input patterns for batch job submission:
ip_start = 1850
ip_end = 2014
ip_step = 1
# Define maximum number of concurrent SLURM jobs:
max_concurrent_jobs = 1
# Define Python virtual environment activation command:
venv_cmd = ""

[inputs]
#Â Define NEMO ocean model filepaths used to construct NEMODataTree object:
nemo_dir = "/g100_work/optim_IAC/research/noc/otooth/OptimESM/data/UKESM1-2-LL/esm-piControl/r1i1p1f1/Omon"
domain_filepath = "/g100/home/userexternal/otooth00/OptimESM/data/CINECA/MOHC/UKESM1_Ofx/domain_cfg_Ofx_UKESM1.nc"
# Create NEMO model grid datasets from CMORISED variables:
cmorised = true
# Domain Properties:
iperio = true
nftype = "F"
read_mask = false
# -- NEMO gridT (scalar) variables -- #
gridT_filepath = [ "${nemo_dir}/thetao/gn/v*/thetao_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc", "${nemo_dir}/so/gn/v*/so_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc" ]
gridT_vars = [ [ "thetao" ], [ "so" ] ]
# -- NEMO U-grid (zonal vector) variables -- #
gridU_filepath = [ "${nemo_dir}/uo/gn/v*/uo_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc", "${nemo_dir}/thkcello/gn/v*/thkcello_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc" ]
gridU_vars = [ [ "uo" ], [ "thkcello" ] ]
# NEMO V-grid (meridional vector) variables:
gridV_filepath = [ "${nemo_dir}/vo/gn/v*/vo_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc", "${nemo_dir}/thkcello/gn/v*/thkcello_Omon_UKESM1-2-LL_esm-piControl_r1i1p1f1_gn_25*.nc" ]
gridV_vars = [ [ "vo" ], [ "thkcello" ] ]

[diagnostics]
# Define diagnostics to be computed using NEMODataTree:
diagnostic = { module = "nemo_pipeline.diagnostics.core", function = "extract_osnap_section" }
kwargs = { include_eiv = false }

[outputs]
# Define NEMO ocean model pipeline output file:
output_dir = "/g100_work/optim_IAC/research/noc/otooth/OptimESM/WP5/data/MOHC/osnap"
output_name = "UKESM1-2-LL_esm-piControl_r1i1p1f1_osnap"
date_format = "M"
format = "netcdf"
# Define output dataset chunking:
chunks = { time_counter = 12 }